# Generated by Django 5.2.6 on 2025-09-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0002_rename_first_name_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desgin',
            name='artworkcol',
        ),
        migrations.RemoveField(
            model_name='desgin',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
