# Generated by Django 5.2.6 on 2025-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0003_remove_desgin_artworkcol_remove_desgin_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.URLField(blank=True, max_length=225, null=True),
        ),
    ]
