# Generated by Django 5.2.6 on 2025-09-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0004_alter_user_profilepic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
