# Generated by Django 5.2.6 on 2025-09-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0005_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desgin',
            name='image_url',
        ),
        migrations.AddField(
            model_name='desgin',
            name='image',
            field=models.ImageField(null=True, upload_to='designs/'),
        ),
    ]
