# Generated by Django 5.2.6 on 2025-09-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0006_remove_desgin_image_url_desgin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
