# Generated by Django 5.2.6 on 2025-09-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0007_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
