# Generated by Django 5.2.6 on 2025-09-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_app', '0009_alter_users_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profilepic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
